name: Build commit artifact

on:
  push:
    branches:
      - master

jobs:
  Building:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install the SFML.
        run: |
          git clone https://github.com/SFML/SFML -b 2.5.x /tmp/sfml
          cd /tmp/sfml
          make && sudo make install
      - name: Build Makefile with CMake
        run: mkdir -p build && cd build && cmake ..
      - name: Build with Makefile
        run: make -C build DungeonIntern
      - name: Archive production artifact
        uses: actions/upload-artifact@v1
        with:
          name: DungeonIntern
          path: build/DungeonIntern
